apps/users/urls.py
# coding:utf-8
from django.conf.urls import url, include
from .views import UserInfoView, UploadImageView, UpdatePwdView, SendEamilCodeView, UpdateEmailView
from .views import MyCourseView, MyFavAuthorView, MyMessageView, MyFavCourseView, UploadView, MyUploadView, MyUploadVideoView

__Author__ = 'eyu Fanne'
__Date__ = '2017/7/27'


urlpatterns = [
    # 用户信息
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),
    # 发送邮箱验证码
    url(r'^sendemail_code/$', SendEamilCodeView.as_view(), name="sendemail_code"),
    # 修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),

    # 我的课程
    url(r'^mycourse/$', MyCourseView.as_view(), name="mycourse"),

    # 我的上传列表
    url(r'^myuploadvideo/$', UploadView.as_view(), name="myuploadvideo"),

    # 上传视频
    url(r'^myupload/$', MyUploadView.as_view(), name="myupload"),
    url(r'^myupload/vidoe/$', MyUploadVideoView.as_view(), name="myvideo"),

    # 我收藏的课程机构
    # url(r'^myfav/org/$', MyFavOrgView.as_view(), name="myfav_org"),

    # 我收藏的讲师
    url(r'^myfav/author/$', MyFavAuthorView.as_view(), name="myfav_author"),

    # 我收藏的课程
    url(r'^myfav/course/$', MyFavCourseView.as_view(), name="myfav_course"),

    # 我的消息
    url(r'^mymessage/$', MyMessageView.as_view(), name="mymessage"),
]

apps/video/urls.py
# -*- coding:utf-8 -*-
__author__ = '@Able.Tiger'
__date__ = '2018/3/26 16:01'
from django.conf.urls import url

from .views import VideoListView, VideoDetailView, VideoCommentsView, AddCommentView, VideoVideo, VideoSearch


urlpatterns = [
	# 视频列表页
	url(r'^video_list/(?P<category_id>\d+)/$', VideoListView.as_view(), name="video_list"),
	# 视频详情页
	url(r'^video_detail/(?P<video_id>\d+)/$', VideoDetailView.as_view(), name="video_detail"),
	# 视频评论也
	url(r'^course_comment/(?P<course_id>\d+)/$', VideoCommentsView.as_view(), name="course_comment"),
	# 添加评论
	url(r'^add_comment/$', AddCommentView.as_view(), name="add_comment"),
	# 视屏播放页
	url(r'^video_video/(?P<video_id>\d+)/$', VideoVideo.as_view(), name="video_video"),
	#搜索
	url(r'^list/(?P<category_id>\d+)/$', VideoSearch.as_view(), name="list"),

]

qiqu_sharing/urls.py
# -*- coding:utf-8 -*-
"""qiqu_sharing URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

import xadmin

from users.views import LoginView, RegisterView, ActiveUserView, ForgetPasswordView, PwdResetView, ModifyPwdView, LogoutView, Index


urlpatterns = [
	url(r'^xadmin/', xadmin.site.urls),
	# url(r'^admin/', admin.site.urls),

	# 登录注册退出找回密码
	# url(r'^$', TemplateView.as_view(template_name='index.html'), name="index"),
	url(r'^$', Index.as_view(), name='index'),
	url(r'^login/$', LoginView.as_view(), name="login"),
	url(r'^logout/$', LogoutView.as_view(), name="logout"),
	url(r'^register/$', RegisterView.as_view(), name="register"),
	url(r'^captcha/', include('captcha.urls')),
	url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='active'),
	url(r'^pwd_reset/(?P<reset_code>.*)/$', PwdResetView.as_view(), name='reset_pwd'),
	url(r'^forget/$', ForgetPasswordView.as_view(), name='forget_pwd'),
	url(r'^modify/$', ModifyPwdView.as_view(), name='modify'),

	# 课程相关配置
	url(r'^video/', include('video.urls', namespace="video")),

	# 用户
	url(r'^users/', include('users.urls', namespace="users")),
	# 用户操作
	url(r'^fav/', include('operation.urls', namespace="operation")),

	# 配置文件上传的访问处理函数
	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

apps/users/models.py
# coding=utf-8
from __future__ import unicode_literals

from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class UserProfile(AbstractUser):
	nick_name = models.CharField\
		(max_length=50, verbose_name=u"昵称", default="")
	birthday = models.DateField\
		(verbose_name=u"生日", null=True, blank=True)
	gender = models.CharField\
		(max_length=10, choices=
		(("male", u"男"), ("female", u"女")), default='female')
	address = models.CharField(max_length=100, default=u"")
	mobile = models.CharField(max_length=11, null=True, blank=True)
	image = models.ImageField\
		(upload_to="image/%Y/%m", default=u"image/default.png", max_length=100)

	class Meta:
		verbose_name = u"用户信息"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return self.username


class EmailVerifyRecord(models.Model):
	code = models.CharField(max_length=20, verbose_name=u"验证码")
	email = models.EmailField(max_length=50, verbose_name=u"邮箱")
	send_type = models.CharField(verbose_name=u"验证码类型", max_length=10, choices=(("register", u"注册"), ("forget", u"找回密码")))
	send_time = models.DateField(verbose_name=u"发送时间", default=datetime.now)

	class Meta:
		verbose_name = u"邮箱验证码"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return '{0}({1})'.format(self.code, self.email)


class PostBar(models.Model):
	user = models.ForeignKey(UserProfile, verbose_name=U"贴吧发言人")
	contents = models.TextField(verbose_name=u"发言内容")
	pid = models.IntegerField(verbose_name=u"父id")
	cid = models.IntegerField(verbose_name=u"子id")
	add_time = models.DateField(default=datetime.now, verbose_name=u"发布时间")

	class Meta:
		verbose_name = u"贴吧留言"
		verbose_name_plural = verbose_name

	def __unicode__(self):
		return self.contents


class Banner(models.Model):
	title = models.CharField(max_length=100, verbose_name=u"标题")
	image = models.ImageField(max_length=100, upload_to="banner/%Y%m", verbose_name=u"轮播图")
	url = models.URLField(max_length=200, verbose_name=u"访问地址")
	index = models.IntegerField(default=100, verbose_name=u"顺序")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

	class Meta:
		verbose_name = u"轮播图"
		verbose_name_plural = verbose_name

apps/users/forms.py
# -*- coding:utf-8 -*-
from users.models import UserProfile
from django import forms
from captcha.fields import CaptchaField

__author__ = '@Able.Tiger'
__date__ = '2018/3/26 14:27'


class LoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, min_length=6)
	# 此处说明：在前端html中，表单的<input name="username">,<input name="password">
	# 其中,LoginFormz中的字段名字要与之对应


class RegisterForm(forms.Form):
	email = forms.EmailField(required=True)
	password = forms.CharField(required=True, min_length=6)
	captcha = CaptchaField(error_messages={'invalid': u'验证码错误'})


class ForgetPasswordForm(forms.Form):
	email = forms.EmailField(required=True)
	captcha = CaptchaField(error_messages={'invalid': u'验证码错误'})


class PwdResetForm(forms.Form):
	password = forms.CharField(required=True, min_length=6)
	password2 = forms.CharField(required=True, min_length=6)


class ModifyPwdForm(forms.Form):
	password1 = forms.CharField(required=True, min_length=5)
	password2 = forms.CharField(required=True, min_length=5)


class UploadImageForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ["image"]


class UploadVideoForm(forms.Form):
	video_name = forms.CharField(required=True)
	video_desc = forms.CharField(required=True)
	video_detail = forms.TextInput()
	video_category = forms.CharField(required=True)
	video_times = forms.CharField(required=True)
	video_image = forms.ImageField(required=True)
	video_video = forms.FileField(required=True)


class UserInfoForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ["nick_name", 'birthday', "gender", "address", "mobile", ]

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
<title> {% block title %}奇趣知识共享{% endblock %} </title>

{% block content %}
    <!--crumbs start-->

        <div class="banner">
                <div class="wp">
                    <div class="fl">
                        <div class="imgslide">
                            <ul class="imgs">

                                <li>
                                        <a href="http://www.imooc.com">
                                            <img width="1200" height="478" src="{% static 'media/banner/01.jpg' %}" />
                                        </a>
                                    </li>

                                <li>
                                        <a href="http://www.projectsedu.com">
                                            <img width="1200" height="478" src="{% static 'media/banner/02.jpg' %}" />
                                        </a>
                                    </li>

                                <li>
                                        <a href="http://www.projectsedu.com">
                                            <img width="1200" height="478" src="{% static 'media/banner/03.jpg' %}" />
                                        </a>
                                    </li>

                                <li>
                                        <a href="http://www.projectsedu.com">
                                            <img width="1200" height="478" src="{% static 'media/banner/04.jpg' %}" />
                                        </a>
                                    </li>

                                <li>
                                        <a href="http://www.projectsedu.com">
                                            <img width="1200" height="478" src="{% static 'media/banner/05.jpg' %}" />
                                        </a>
                                    </li>


                            </ul>
                        </div>
                        <div class="unslider-arrow prev"></div>
                        <div class="unslider-arrow next"></div>
                    </div>

                    </div>


                </div>
    <!--banner end-->
    <!--feature start-->
        <section>
            <div class="wp">
                <ul class="feature">
                    <li class="feature1">
                        <img class="pic" src="{% static 'images/feature1.png' %}"/>
                        <p class="center">奇趣知识</p>
                    </li>
                    <li class="feature2">
                        <img class="pic" src="{% static 'images/feature2.png' %}"/>
                        <p class="center">美味吃货</p>
                    </li>
                    <li class="feature3">
                        <img class="pic" src="{% static 'images/feature3.png' %}"/>
                        <p class="center">强身健体</p>
                    </li>
                    <li class="feature4">
                        <img class="pic" src="{% static 'images/feature4.png' %}"/>
                        <p class="center">生活技巧</p>
                    </li>
                </ul>
            </div>
        </section>
    <!--feature end-->
    <!--module1 start-->
         <!--
            描述：美味厨艺
         -->
        <section>

            <div class="module">
                <div class="wp">
                    <h1>美味厨艺</h1>
                    <div class="module1 eachmod">
                        <div class="module1_1 left">
                            <img width="228" height="614" src="{% static 'media/meiwei/舌尖.jpg' %}"/>
                            <p class="fisrt_word">美味厨艺<br/>专业吃货</p>
                            <a class="more" href="{% url 'video:video_list' 1 %}">查看更多 ></a>
                        </div>
                        <div class="right group_list">
                            <div class="module1_2 box">
                                <div class="imgslide2">
                                    <ul class="imgs">
                                        {% for banner_list in banner_chuyi_lists %}
                                            <li>
                                            <a href="{% url 'video:video_detail' banner_list.id %}">
                                                <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_list.image }}" />
                                            </a>
                                        </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                                <div class="unslider-arrow2 prev"></div>
                                <div class="unslider-arrow2 next"></div>
                            </div>


                                {% for chuyi_list in chuyi_lists %}
                                    <div class="module1_3 box">
                                    <a href="{% url 'video:video_detail' chuyi_list.id %}">
                                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ chuyi_list.image }}"/>
                                    </a>
                                    <div class="des">
                                        <a href="video-detail.html">
                                            <h2 title="django入门">{{ chuyi_list.name }}</h2>
                                        </a>
                                        <span class="fl">星级：<i class="key">{{ chuyi_list.get_degree_display }}</i></span>
                                        <span class="fr">学习人数：{{ chuyi_list.students }}</span>
                                    </div>
                                    <div class="bottom">
                                        <span class="fl" title="慕课网">{{ chuyi_list.author }}</span>
                                        <span class="star fr">{{ chuyi_list.click_nums }}</span>
                                    </div>
                                   </div>
                                {% endfor %}



                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--
            作者：1402240120@qq.com
            时间：2018-03-21
            描述：生活技巧
        -->
        <section>

            <div class="module">
                <div class="wp">
                    <h1>生活技巧</h1>
                    <div class="module1 eachmod">
                        <div class="module1_1 left">
                            <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                            <p class="fisrt_word">生活技巧<br/>生活乐趣</p>
                            <a class="more" href="{% url 'video:video_list' 2 %}">查看更多 ></a>
                        </div>

                        <div class="right group_list">
                            <div class="module1_2 box">
                                <div class="imgslide2">
                                    <ul class="imgs">

                                        {% for banner_list in banner_shenghuo_lists %}
                                            <li>
                                            <a href="{% url 'video:video_detail' banner_list.id %}">
                                                <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_list.image }}" />
                                            </a>
                                        </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                                <div class="unslider-arrow2 prev"></div>
                                <div class="unslider-arrow2 next"></div>
                            </div>

                                {% for chuyi_list in shenghuo_lists %}
                                    <div class="module1_3 box">
                                    <a href="{% url 'video:video_detail' chuyi_list.id %}">
                                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ chuyi_list.image }}"/>
                                    </a>
                                    <div class="des">
                                        <a href="video-detail.html">
                                            <h2 title="django入门">{{ chuyi_list.name }}</h2>
                                        </a>
                                        <span class="fl">星级：<i class="key">{{ chuyi_list.get_degree_display }}</i></span>
                                        <span class="fr">学习人数：{{ chuyi_list.students }}</span>
                                    </div>
                                    <div class="bottom">
                                        <span class="fl" title="慕课网">{{ chuyi_list.author }}</span>
                                        <span class="star fr">{{ chuyi_list.click_nums }}</span>
                                    </div>
                                   </div>
                                {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--
            作者：1402240120@qq.com
            时间：2018-03-21
            描述：强身健体
        -->
        <section>

            <div class="module">
                <div class="wp">
                    <h1>强身健体</h1>
                    <div class="module1 eachmod">
                        <div class="module1_1 left">
                            <img width="228" height="614" src="{% static 'images/liyi.jpg' %}"/>
                            <p class="fisrt_word">强身健体<br/>健康生活</p>
                            <a class="more" href="{% url 'video:video_list' 3 %}">查看更多 ></a>
                        </div>
                        <div class="right group_list">
                            <div class="module1_2 box">
                                <div class="imgslide2">
                                    <ul class="imgs">

                                        {% for banner_list in banner_liyi_lists %}
                                            <li>
                                            <a href="{% url 'video:video_detail' banner_list.id %}">
                                                <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_list.image }}" />
                                            </a>
                                        </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                                <div class="unslider-arrow2 prev"></div>
                                <div class="unslider-arrow2 next"></div>
                            </div>

                            {% for chuyi_list in liyi_lists %}
                                    <div class="module1_3 box">
                                    <a href="{% url 'video:video_detail' chuyi_list.id %}">
                                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ chuyi_list.image }}"/>
                                    </a>
                                    <div class="des">
                                        <a href="video-detail.html">
                                            <h2 title="django入门">{{ chuyi_list.name }}</h2>
                                        </a>
                                        <span class="fl">星级：<i class="key">{{ chuyi_list.get_degree_display }}</i></span>
                                        <span class="fr">学习人数：{{ chuyi_list.students }}</span>
                                    </div>
                                    <div class="bottom">
                                        <span class="fl" title="慕课网">{{ chuyi_list.author }}</span>
                                        <span class="star fr">{{ chuyi_list.click_nums }}</span>
                                    </div>
                                   </div>
                                {% endfor %}


                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

{% block custom_js %}
     <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <script>

        for(var i=0;i<3;i++){
            $(".group_list .box").eq(2+i*7).css("marginRight","0");
            $(".group_list .box").eq(6+i*7).css("marginRight","0");
            $(".group_list .box").eq(3+i*7).css("marginTop","10px");
            $(".group_list .box").eq(4+i*7).css("marginTop","10px");
            $(".group_list .box").eq(5+i*7).css("marginTop","10px");
            $(".group_list .box").eq(6+i*7).css("marginTop","10px");
        }
</script>
{% endblock %}

templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password" value="{{ reset_pwd_form.password.value }}" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name='email' value="{{ email }}">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交" onclick="reset_password_form_submit()">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/usercenter-fav-course.html
{% extends "usercenter-base.html" %}
{% block title %}

{% endblock %}
{%load staticfiles %}
{% block custom_bread %}
<section>
<div class="wp">
    <ul  class="crumbs">
        <li><a href="{% url 'index' %}">首页</a>></li>
        <li><a href="/user/home/">个人中心</a>></li>
        <li>我的收藏</li>
    </ul>
</div>
</section>
{% endblock %}

{% block right_content %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_author' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">        

                        {% for course in course_list.object_list %}

                        <div class="module1_5 box">
                            <a href="{% url 'video:video_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'video:video_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="12"></span>
                            </div>
                        </div>

                        {% endfor %}

                    </div>
                </div>

                <div class="pageturn">
                            <ul class="pagelist">
                            {% if user_videos.has_previous %}
                                <li class="long"><a href="?{{ user_videos.previous_page_number.querystring }}">上一页</a></li>
                            {% endif %}
                            {% for page in user_videos.pages %}
                                {% if page %}
                                    {% ifequal page user_videos.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li ><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                     <li class="none"><a href="" >...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if user_videos.has_next %}
                                 <li class="long"><a href="?{{ user_videos.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}

                        </ul>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-info.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block title %}
    <title>个人信息-奇趣知识共享</title>
{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="/user/home/">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>

			    <div class="inforcon">
				    <div class="left" style="width:242px;">
                        <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                        <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                            <label class="changearea" for="avatarUp">
                                <span id="avatardiv" class="pic">
                                    <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                </span>
                                <span class="fl upload-inp-box" style="margin-left:70px;">
                                    <span class="button btn-green btn-w100" id="
                                    jsAvatarBtn">修改头像</span>
                                    <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                                </span>
                            </label>
                            <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                            {% csrf_token %}
                        </form>
                        <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                            <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                        </div>
                    </div>
				    <form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birthday" value="{{ request.user.birthday }}" />
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="{{ request.user.gender }}" {% if request.user.gender == 'male' %}checked="male"{% endif %}>男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="{{ request.user.gender }}" {% if request.user.gender == 'female' %}checked="female"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile }}" maxlength="11">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email"  value="{{ request.user.mail }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                        {% csrf_token %}
				</form>
			    </div>

		</div>
	</div>
{% endblock %}